#!/bin/sh

if [ "$#" -ne 2 ]; then
    echo ""
    echo "Usage: bash run-all-xpolicy <group_member> <repl_policy>"
    echo "    group_member: "
    echo "      -- Zach"
    echo "      -- Rodrigo"
    echo "      -- Brycen"
    echo "    repl_policy: LRU LFU SRRIP ST-RRIP Mockingjay"
else
    group_member=$1
    repl=$2

    # Define benchmarks for each group member
    case $group_member in
        "Zach")
            benchmarks="gcc xalancbmk namd bodytrack swaptions soplex x264"
            ;;
        "Rodrigo")
            benchmarks="bzip2 hmmer calculix fluidanimate sjeng lbm"
            ;;
        "Brycen")
            benchmarks="mcf cactus blackscholes streamcluster libquantum canneal"
            ;;
        *)
            echo "Unknown group member. Please specify either Zach, Rodrigo, or Brycen."
            exit 1
            ;;
    esac

    # Run the entire set of benchmarks in the background
    (
        # Loop through the selected benchmarks and execute them sequentially
        for bench in $benchmarks; do
            mkdir -p outputs/hw4/$repl/${bench}
            echo "./build/opt/zsim configs/hw4/$repl/${bench}.cfg > outputs/hw4/$repl/${bench}/${bench}.log 2>&1"
            ./build/opt/zsim configs/hw4/$repl/${bench}.cfg > outputs/hw4/$repl/${bench}/${bench}.log 2>&1 &
            
            # Capture the PID of the zsim process
            zsim_pid=$!
            
            # Wait for the specific zsim PID to finish
            wait $zsim_pid
        done
    ) &  # Run the entire block in the background
fi
