#!/bin/sh

if [ "$#" -ne 3 ]; then
    echo ""
    echo "Usage: ./run-simulation <suite> <benchmark> <repl_policy>"
    echo "    (suite) benchmarks: "
    echo "      -- (SPEC) bzip2 gcc mcf hmmer xalan cactusADM leslie3d namd calculix sjeng libquantum soplex lbm"
    echo "      -- (PARSEC) blackscholes bodytrack fluidanimate streamcluster swaptions canneal x264"
    echo "    repl_policy: LRU LFU SRRIP ST-RRIP WeiSub"
else
    suite=$1
    bench=$2
    repl=$3

    # your simulation results will be saved to outputs/$repl/$bench/
    if [ "$suite" = "SPEC" ]; then
        mkdir -p outputs/$repl/${bench}
        echo "./build/opt/zsim configs/$repl/${bench}.cfg > outputs/$repl/${bench}/${bench}.log 2>&1 &"
        ./build/opt/zsim configs/$repl/${bench}.cfg > outputs/$repl/${bench}/${bench}.log 2>&1 &
    elif [ "$suite" = "PARSEC" ]; then
        mkdir -p outputs/$repl/${bench}_8c_simlarge
        echo "./build/opt/zsim configs/$repl/${bench}_8c_simlarge.cfg > outputs/$repl/${bench}_8c_simlarge/${bench}.log 2>&1 &"
        ./build/opt/zsim configs/$repl/${bench}_8c_simlarge.cfg > outputs/$repl/${bench}_8c_simlarge/${bench}.log 2>&1 &
    else
        echo "No such benchmark suite, please specify SPEC or PARSEC"
    fi
fi
